M48
; DRILL file {KiCad 7.0.6-1.fc38} date Thu 24 Aug 2023 06:59:45 PM MST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-24T18:59:45-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-1.fc38
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.2460
%
G90
G05
T1
X4.245Y-1.458
X4.245Y-6.282
X6.455Y-1.458
X6.455Y-6.282
T2
X4.3Y-4.1
X4.3Y-4.8
X6.4Y-4.1
X6.4Y-4.8
T0
M30
